<?php

/**
 * Test: Nette\DI\Config\Adapters\NeonAdapter
 */

declare(strict_types=1);

use Nette\DI\Config;
use Nette\DI\Definitions\Reference;
use Nette\DI\Definitions\Statement;
use Tester\Assert;


require __DIR__ . '/../bootstrap.php';

define('TEMP_FILE', getTempDir() . '/cfg.neon');


$config = new Config\Loader;
$data = $config->load('files/neonAdapter.neon');
Assert::same([
	'section' => [
		'webname' => 'the example',
		'database' => [
			'adapter' => 'pdo_mysql',
			'params' => [
				'host' => 'db.example.com',
				'username' => 'dbuser',
				'password' => 'secret',
				'dbname' => 'dbname',
			],
		],
		'timeout' => 10,
		'display_errors' => true,
		'html_errors' => false,
		'items' => [10, 20],
		'php' => ['zlib.output_compression' => true, 'date.timezone' => 'Europe/Prague'],
	],
	'override' => [],
	'nothing' => null,
], $data);


$config->save($data, TEMP_FILE);
Assert::match(<<<'EOD'
# generated by Nette

section:
	webname: the example
	database:
		adapter: pdo_mysql
		params:
			host: db.example.com
			username: dbuser
			password: secret
			dbname: dbname

	timeout: 10
	display_errors: true
	html_errors: false
	items:
		- 10
		- 20

	php:
		zlib.output_compression: true
		date.timezone: Europe/Prague

override: []
nothing: null
EOD
, file_get_contents(TEMP_FILE));


$cfg = '
- ent(1)
- ent(2)inner(3, 4)
- ent(3)::inner(5)
';
$data = $config->load(Tester\FileMock::create($cfg, 'neon'));
Assert::equal([
	new Statement('ent', [1]),
	new Statement(
		[
			new Statement('ent', [2]),
			'inner',
		],
		[3, 4]
	),
	new Statement(
		[
			new Statement('ent', [3]),
			'inner',
		],
		[5]
	),
], $data);


$config->save($data, TEMP_FILE);
Assert::match(<<<'EOD'
# generated by Nette

- ent(1)
- ent(2)::inner(3, 4)
- ent(3)::inner(5)
EOD
, file_get_contents(TEMP_FILE));


$data = $config->load('files/neonAdapter.save.neon');
$config->save($data, TEMP_FILE);
Assert::match(<<<'EOD'
# generated by Nette

parameters:
	type: Ipsum

services:
	referencedService: @one
	referencedServiceWithSetup:
		factory: @one
		setup:
			- $x(10)

	serviceAsParam: Ipsum(@one)
	calledService: @one()
	calledServiceWithArgs: @one(1)
	calledServiceAsParam: Ipsum(@one())
	calledServiceWithArgsAsParam: Ipsum(@one(1))
	one:
		type: %class%
		arguments:
			- 1

	two:
		factory: %class%(1)

	three:
		type: Lorem
		factory: Factory::createLorem
		arguments:
			- 1

	four:
		factory: Factory::createLorem(1)

	five:
		factory: Factory::createLorem(1)

	six: Factory::createLorem(1)
	seven: @factory
	eight: @factory()
	nine:
		- @three
		- foo

	stdClass: stdClass
	factory: Lorem
	rich1: Lorem(1)::foo()
	rich2:
		factory: Lorem(Ipsum(@one))::foo(1)

	rich3: Factory::createLorem(1)::foo()
	rich4: Factory()::createLorem(1)::foo()
	- Lorem(1)::foo()

EOD
, file_get_contents(TEMP_FILE));


$data = [
	'a' => new Statement([new Reference('foo'), 'method'], [new Reference('bar')]),
	'b' => new Statement(new Reference('foo')),
];
$config->save($data, TEMP_FILE);
Assert::match(<<<'EOD'
# generated by Nette

a: @foo::method(@bar)
b: @foo()
EOD
, file_get_contents(TEMP_FILE));
