<?php
declare(strict_types=1);

namespace Nette\Bridges\DITracy;

use Nette;
use Tracy\Dumper;
use Tracy\Helpers;

$snapshot = [];

?>
<style class="tracy-debug">
	#tracy-debug .nette-ContainerPanel table {
		width: 100%;
		white-space: nowrap;
	}

	#tracy-debug .nette-ContainerPanel .created {
		font-weight: bold;
	}

	#tracy-debug .nette-ContainerPanel .yes {
		color: green;
		font-weight: bold;
	}
</style>

<h1><?= get_class($container) ?></h1>

<div class="tracy-inner nette-ContainerPanel">
<div class="tracy-inner-container">
	<h2>Services</h2>

	<table>
		<thead>
		<tr>
			<th>Name</th>
			<th>Autowired</th>
			<th>Service</th>
			<th>Tags</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($types as $name => $type): ?>
		<?php $name = (string) $name ?>
		<?php $autowired = in_array($name, array_merge($wiring[$type][1] ?? [], $wiring[$type][2] ?? []), true) ?>
		<tr>
			<td class="<?= isset($instances[$name]) ? 'created' : '' ?>"><?= is_numeric($name) ? "<span title='$name'>–</span>" : htmlspecialchars($name) ?></td>
			<td class="<?= $autowired ? 'yes' : '' ?>"><?= $autowired ? 'yes' : 'no' ?></td>
			<td>
				<?php if (isset($instances[$name]) && !$instances[$name] instanceof Nette\DI\Container): ?>
					<?= Dumper::toHtml($instances[$name], [Dumper::COLLAPSE => true, Dumper::SNAPSHOT => &$snapshot]); ?>
				<?php elseif (isset($instances[$name])): ?>
					<code><?= get_class($instances[$name]) ?></code>
				<?php elseif (is_string($type)): ?>
					<code><?= htmlspecialchars($type) ?></code>
				<?php endif ?>
			</td>
			<td><?php if (isset($tags[$name])) { echo Dumper::toHtml($tags[$name], [Dumper::COLLAPSE => true]); } ?></td>
		</tr>
		<?php endforeach ?>
		</tbody>
	</table>

	<meta itemprop=tracy <?= Dumper::formatSnapshotAttribute($snapshot) ?>>

	<h2>Parameters</h2>

	<div class="nette-ContainerPanel-parameters">
		<?= Dumper::toHtml($container->parameters); ?>
	</div>

	<p>Source: <?= Helpers::editorLink($file) ?></p>
</div>
</div>
