<?php

/**
 * This file is part of the Nette Framework (https://nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace Nette\DI\Config\Adapters;

use Nette;
use Nette\DI\Config\Helpers;


/**
 * Reading and generating INI files.
 */
final class IniAdapter implements Nette\DI\Config\IAdapter
{
	use Nette\SmartObject;

	private const
		KEY_SEPARATOR = '.', // key nesting key1.key2.key3
		ESCAPED_KEY_SEPARATOR = '..',
		RAW_SECTION = '!';


	/**
	 * Reads configuration from INI file.
	 * @param  string  file name
	 * @throws Nette\InvalidStateException
	 */
	public function load(string $file): array
	{
		$ini = @parse_ini_file($file, true); // @ escalated to exception
		if ($ini === false) {
			$error = error_get_last();
			throw new Nette\InvalidStateException("parse_ini_file(): $error[message]");
		}
		return $this->process($ini);
	}


	/**
	 * @throws Nette\InvalidStateException
	 */
	public function process(array $arr): array
	{
		$data = [];
		foreach ($arr as $secName => $secData) {
			if (is_array($secData)) { // is section?
				if (substr($secName, -1) === self::RAW_SECTION) {
					$secName = substr($secName, 0, -1);
				} else { // process key nesting separator (key1.key2.key3)
					$tmp = [];
					foreach ($secData as $key => $val) {
						$cursor = &$tmp;
						$key = str_replace(self::ESCAPED_KEY_SEPARATOR, "\xFF", $key);
						foreach (explode(self::KEY_SEPARATOR, $key) as $part) {
							$part = str_replace("\xFF", self::KEY_SEPARATOR, $part);
							if (!isset($cursor[$part]) || is_array($cursor[$part])) {
								$cursor = &$cursor[$part];
							} else {
								throw new Nette\InvalidStateException("Invalid key '$key' in section [$secName].");
							}
						}
						$cursor = $val;
					}
					$secData = $tmp;
				}
			}

			$cursor = &$data; // nesting separator in section name
			foreach (explode(self::KEY_SEPARATOR, $secName) as $part) {
				if (!isset($cursor[$part]) || is_array($cursor[$part])) {
					$cursor = &$cursor[$part];
				} else {
					throw new Nette\InvalidStateException("Invalid section [$secName].");
				}
			}

			if (is_array($secData) && is_array($cursor)) {
				$secData = Helpers::merge($secData, $cursor);
			}

			$cursor = $secData;
		}

		return $data;
	}


	/**
	 * Generates configuration in INI format.
	 */
	public function dump(array $data): string
	{
		$output = [];
		foreach ($data as $name => $secData) {
			if (!is_array($secData)) {
				$output = [];
				self::build($data, $output, '');
				break;
			}
			$output[] = "[$name]";
			self::build($secData, $output, '');
			$output[] = '';
		}
		return "; generated by Nette\n\n" . implode(PHP_EOL, $output);
	}


	/**
	 * Recursive builds INI list.
	 */
	private static function build($input, &$output, $prefix): void
	{
		foreach ($input as $key => $val) {
			$key = str_replace(self::KEY_SEPARATOR, self::ESCAPED_KEY_SEPARATOR, $key);
			if (is_array($val)) {
				self::build($val, $output, $prefix . $key . self::KEY_SEPARATOR);

			} elseif (is_bool($val)) {
				$output[] = "$prefix$key = " . ($val ? 'true' : 'false');

			} elseif (is_numeric($val)) {
				$output[] = "$prefix$key = $val";

			} elseif (is_string($val)) {
				$output[] = "$prefix$key = \"$val\"";

			} else {
				throw new Nette\InvalidArgumentException(sprintf("The '%s' item must be scalar or array, %s given.", $prefix . $key, gettype($val)));
			}
		}
	}
}
