<?php declare(strict_types=1);

/**
 * This file is part of the Nette Framework (https://nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

namespace Nette\DI\Config\Adapters;

use Nette;
use Nette\DI\Compiler;


/**
 * Reading and generating PHP files.
 */
final class PhpAdapter implements Nette\DI\Config\Adapter
{
	/**
	 * Reads configuration from PHP file. A file returning a closure (operating on Definitions) is
	 * wrapped into an internal section so it flows through the array-based loader to the Compiler.
	 */
	public function load(string $file): array
	{
		$data = require $file;
		return $data instanceof \Closure
			? [Compiler::Closures => [$data]]
			: $data;
	}


	/**
	 * Generates configuration in PHP format.
	 * @param  array<string, mixed>  $data
	 */
	public function dump(array $data): string
	{
		return "<?php // generated by Nette \nreturn " . (new Nette\PhpGenerator\Dumper)->dump($data) . ';';
	}
}
